libraryDependencies += "com.google.cloud" % "google-cloud-pubsub" % "0.9.2-alpha"
libraryDependencies += "com.google.apis" % "google-api-services-oauth2" % "v2-rev124-1.22.0"
libraryDependencies += "com.google.apis" % "google-api-services-pubsub" % "v1-rev350-1.22.0"
libraryDependencies += "com.google.api-client" % "google-api-client" % "1.22.0"
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging" % "3.5.0"
libraryDependencies += "org.slf4j" % "slf4j-simple" % "1.7.23"
libraryDependencies += "javax.servlet" % "javax.servlet-api" % "3.1.0"
